- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - tripleo-build-containers-jobs
